apiVersion: v1
kind: Pod
metadata:
  name: emptydir
spec:
  containers:
      - name: container1
        image: ubuntu
        command: ["/bin/bash", "-c", "while true; do echo This is Day13 of 30DaysOfKubernetes;sleep 5 ; done"]
        volumeMounts:
          - name: vol-1
            mountPath: "/tmp/container1"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
      - name: container2
        image: centos
        command: ["/bin/bash", "-c", "while true; do echo Chak de INDIA!; sleep 5 ; done"]
        volumeMounts:
          - name: vol-1
            mountPath: "/tmp/container2"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
  volumes:
      - name: vol-1
        emptyDir: {}

#what ever u created in container1 folder, it will appear in container2 also. vice versa also.
# kubectl exec -it emptydir -c container2 -- bash