apiVersion: v1
kind: Pod
metadata:
  name: hostpath
spec:
  containers:
  - name: container1
    image: ubuntu
    command: ["/bin/bash", "-c", "while true; do echo This is Day13 of 30DaysOfKubernetes;sleep 5 ; done"]
    resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
    volumeMounts:
    - mountPath: "/tmp/cont"
      name: vol-1                                                    #vol name
  volumes:
    - name: vol-1
      hostPath:
        path: /tmp/data


# /tmp/data on your host(where pod is created) and /tmp/cont on your container will sync.