apiVersion: v1
kind: PersistentVolume
metadata:
  name: myebsvol
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  awsElasticBlockStore:
      volumeID: xxxxxx               #EBS volume
      fsType: ext

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myebsvolclaim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pvdeploy
spec:
  replicas: 1
  selector:
      matchLabels:
            app: mypv
  template:
      metadata:
        labels:
            app: mypv
      spec:
        containers:
            - name: shell
              image: centos
              command: ["bin/bash", "-c", "sleep 10000"]
              resources:
                limits:
                  memory: "128Mi"
                  cpu: "500m"
              volumeMounts:
                - name: mypd
                  mountPath: "/tmp/persistent"
        volumes:
              - name: mypd
                persistentVolumeClaim:
                  claimName: myebsvolclaim