apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-nodejs-app
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: container1
        image: chowdarybvsn/simple-nodejs-app:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"