apiVersion: v1
kind: Service
metadata:
  name: simple-nodejs-app-service
spec:
  selector:
    app: myapp  # This matches the label defined in the deployment
  ports:
    - protocol: TCP
      port: 80         # External port the service will listen on
      targetPort: 8080  # Port on the container
      nodePort: 30000
  type: NodePort

#controlplane $ curl http://10.99.203.206:80     (svc IP)
#               Hello from Node.js!

#controlplane $ curl http://localhost:30000      (node/server IP also u can use instead of localhost)
#               Hello from Node.js!

# even it is same from any node/server in cluster