apiVersion: v1
kind: Service
metadata:
  name: simple-nodejs-app-service
spec:
  selector:
    app: myapp # This matches the label defined in the deployment
  ports:
    - protocol: TCP
      port: 80
  type: ClusterIP