apiVersion: v1
kind: Service
metadata:
  name: simple-nodejs-app-service
spec:
  selector:
    app: myapp  # This matches the label defined in the deployment
  ports:
    - protocol: TCP
      port: 80         # External port the service will listen on
      targetPort: 8080  # Port on the container
      nodePort: 30000
  type: NodePort